baseURL = "https://jyannick.github.io/bieres/"
languageCode = "fr-fr"
title = "Les Bières de Yannick"
theme = "themeDeYannick"
publishDir = "docs"
pluralizelisttitles = false

[params]
  welcome = "Brassage maison et références obscures"
  icon = "beer"
  moreText = "(suite...)"

[menu]
  [[menu.main]]
    name = "Bières"
    pre = "wine-bottle"
    url = "/bieres/"
    weight = 1
  [[menu.main]]
    name = "Brassage"
    pre = "flask"
    url = "/brassage/"
    weight = 2
