baseURL = "https://jyannick.github.io/bieres/"
languageCode = "fr-fr"
title = "Les Bières de Yannick"
theme = "themeDeYannick"
publishDir = "docs"

[params]
  welcome = "Brassage maison et références obscures"

[menu]
  [[menu.main]]
    name = "Accueil"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Bières"
    pre = "wine-bottle"
    url = "/bieres/"
    weight = 2
  [[menu.main]]
    name = "Brassage"
    pre = "flask"
    url = "/brassage/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    pre = "user-edit"
    url = "/posts/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 5